name: 'Build App'

on:
  push:
    branches:
      - '**'

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Add Rust build targets (macOS only)
        if: matrix.platform == 'macos-latest'
        run: rustup target add aarch64-apple-darwin x86_64-apple-darwin

      - name: Install Dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install Frontend Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build App (macOS)
        if: matrix.platform == 'macos-latest'
        uses: tauri-apps/tauri-action@v0
        with:
          args: --target universal-apple-darwin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build App (Others)
        if: matrix.platform != 'macos-latest'
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifacts (macOS)
        if: matrix.platform == 'macos-latest'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform }}
          path: ./src-tauri/target/universal-apple-darwin/release/bundle/

      - name: Upload Artifacts (Others)
        if: matrix.platform != 'macos-latest'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform }}
          path: ./src-tauri/target/release/bundle/
